version: '3.3'
services:
    web:
        build:
          context: ./
          dockerfile: WebServer.DockerFile
        ports:
          -  "80:80"
          -  "8080:80"
    mysql:
        build:
          context: ./
          dockerfile: SQL.DockerFile
        ports:
          -  "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'